# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    secret_key: genderfluidityisthenewqueer
    source: https://registry-1.docker.io

dev:
    storage: local
    storage_path: /tmp/registry
    loglevel: debug
