# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    secret_key: REPLACEME
    source: https://registry-1.docker.io
    source_index: https://index.docker.io
    tags_cache:
        enabled: true
        ttl: 240       # hours

dev:
    storage: local
    storage_path: /tmp/registry
    loglevel: debug
    cache: true